### ISSUE TITLE
Stargazer Question

### ISSUE THREAD

**Issue by RedCup217** [ericbright2002/Forged_in_Obsidian#1]
Could the JSON in this be used in Stargazer? If not, where would I be able to find it?

**Comment by ericbright2002** [comment]
The short answer is no.  Stargazer's oracles are not accessible via JSON upload, so you won't be able to add the expanded oracles to the normal oracles.  I mentioned it on discord, but the author of Stargazer does not intend at this time to open up the regular oracles to be expanded.

The long answer is: maybe, if you can handle the pain of Stargazer's interface after the upload.  It is possible to use this JSON file to create a new JSON file for upload to Stargazer, but all 300+ oracles would be located in the single Custom dropdown menu.  If you roll on the normal Action/Theme oracle, you wouldn't get the expanded options because the normal oracles are locked down.  You'd have to go to the Custom tab, and then select Action/Theme from there.  With all 300+ oracles in that one dropdown, you'd be scrolling all day to find the right oracles, so I wouldn't recommend uploading my expanded oracles to Stargazer at this time.  Maybe if he opens up the code a bit more so you can edit the normal oracles, then I can get everything in shape.  

If you really have your heart set on it, you'd need to make some changes to my JSON file which include:
     1. Add a UUID to each oracle
     2. Change the dice entry from "300" to "1d300"
     3. Change the category entry to "Custom"

If you really want that, let me know, and I'll see if I can find some time to automate the necessary changes.

**Comment by RedCup217** [comment]
Thank you for your answer! I'll keep doing what I've been doing. Roll in the app and fill it in from your pdf. 

I've been using the Obsidian build, though. MUCH better than mine! Lol
