### ISSUE TITLE
Not all moves need a stat to be rolled

### ISSUE THREAD

**Issue by xavierroy** [ericbright2002/Forged_in_Obsidian#2]
Some moves like Begin/End a session do not need a stat for a roll. But the inline script requires a stat and adds for a roll. IS there a chance to exclude these rolls from not needing a stat or adds?

**Comment by ericbright2002** [comment]
The "move" command is explicitly for moves that require a roll.  For all the other moves, I would suggest one of the following options:

- If you're making another move, such as Begin a Session, that has an oracle table with it, you should roll on that table using either the "oracle" command or the vanilla inline scripts command of "tbl roll". 
- If you're making the move and want to note it in your fiction, you can use the "moveref" command to embed the wording of that move as a callout box. 
- If you're using a move that neither rolls an oracle nor makes a roll, you can use the "mech" to pull up a generic mechanics box with which to write your outcome.
- Pay the Price has its own command of "ptp" since it happens so often.

I think that covers all the bases.  Is there something I'm missing?

**Comment by xavierroy** [comment]
Got it. Thank you for the clarification and the vault too.
