### ISSUE TITLE
Rolls stopped taking the stats from Character sheet.

### ISSUE THREAD

**Issue by Nepturnal** [ericbright2002/Forged_in_Obsidian#6]
The vault won't recognize what's written in the frontmatter on the Character sheet:

On Windows, I have all my stats put there, but under that in the tables of Stats and Meters it just displays "-": 
when I go there with the cursor and highlight it all, it still reads:
 | `=this.Edge` | `=this.Heart` | `=this.Iron` | `=this.Shadow` | `=this.Wits` | etc, 
it still shows the right values when I remain in the same row and scrub over them with the text cursor, but as soon as it goes back to a table view it's back with the " - ".
In Impacts, the table shows just the name of the contidion with a en-dash before it in the table, like: - Wounded.
As with before, when the table is selected the `=this.Wounded` is there, and when I scrub over it with the cursor it shows the correct icons, but as soon as it exits the code view it stops working.
The rest of it works fine, but when I go to make rolls it won't automatically use the stats, but just zero.

On android the tables are visible as they should be, I still see the stats in the table view, but the rolls won't take the stats from there.

I keep my vault synchronized in 3 devices: a computer, a windows tablet and an android phone. 
I use Synchthis to do it and it never gave me an issute, so I don't think that this is the problem.

**Comment by ericbright2002** [comment]
Displaying =this.Edge is an issue with the Dataview plugin not refreshing.  After making changes to stats, move off the page and then back onto.  That usually jolts Dataview into a correct display.  It also can be the mode you're in.  I'm always in editing mode, but read mode should update the character sheet table better.

As for the rolls not working, just to clarify, do you mean the rolls worked previously and now they don't?  I'm not seeing a problem on my end, so it could be a couple of things:

1. Your YAML header got messed up.  Check to make sure you have the three dashes --- at the top and bottom of the frontmatter at the top of the file.
2. The stats aren't named correctly in the frontmatter.  Check to make sure you have 'Edge' instead of 'edge', etc.
3. There could be a space after the number value of a stat messing things up.  For example, 'Edge: 3' is ok, but 'Edge: 3 ' is not because of the extra space.
4. If playing with a single character, is the character file the top file in the 'Characters' folder?  If playing with multiple characters, are you giving the character filename as part of the input?

Those are some of the things I can think of off the top of my head that it could be.  Can you check on those things?  I'll try to recreate the error on my end as well.

**Comment by Nepturnal** [comment]
It's now working! It was late last night and I completely forgot to check between all the tries that the rolls were working again, so I'm sorry about that!

I checked what you told me and everthing was as it should be, I switched to read mode and it updated the tables, so they actually worked as intended, but the rolls still weren't registering my stats, it still put a zero as the stat value.

You told me that the Dataview plugin could be part of the problem: turning the vault to restricted mode and back on didn't help, so I basically unistalled all the plugins and reinstalled them and it's now working.

I'm sorry for bothering you and not thinking about doing this first - I know things sometimes need a nice good reset button, but I'm very new to obsidian and I don't really know what to do.
